-- pgTAP contract checks; run with `supabase test db`.
begin;
select plan(33);
select has_table('public','workspaces','workspaces exist');
select has_table('public','workspace_members','workspace memberships exist');
select has_table('public','profiles','profiles exist');
select has_table('public','conversations','conversations exist');
select has_table('public','messages','messages exist');
select has_table('public','tasks','tasks exist');
select has_table('public','task_events','task events exist');
select has_table('public','availability_slots','availability slots exist');
select has_table('public','reservations','reservations exist');
select has_table('public','outbound_outbox','outbox exists');
select has_table('public','workflow_jobs','workflow jobs exist');
select has_table('public','provider_events','provider events exist');
select has_table('public','audit_logs','audit logs exist');
select has_table('public','simulations','simulations exist');
select has_function('public','is_workspace_member',array['uuid'],'membership helper exists');
select has_function('public','reserve_availability',array['uuid','uuid','text','text','timestamp with time zone'],'atomic reservation exists');
select has_function('public','apply_task_version',array['bigint','text','uuid'],'optimistic concurrency exists');
select has_function('public','ingest_inbound_event',array['uuid','text','text','jsonb','text','text','text','timestamp with time zone'],'atomic inbound ingestion exists');
select has_function('public','release_reservation',array['uuid'],'reservation release exists');
select has_function('public','claim_workflow_jobs',array['uuid','integer','timestamp with time zone'],'atomic job claim exists');
select has_function('public','claim_outbound_messages',array['uuid','integer','timestamp with time zone'],'atomic outbound claim exists');
select has_function('public','transition_task',array['uuid','bigint','text','text','uuid','jsonb'],'atomic task transition exists');
select has_column('public','workflow_jobs','lease_token','workflow job lease token exists');
select has_column('public','workflow_jobs','lease_until','workflow job lease expiry exists');
select col_is_unique('public','messages',array['workspace_id','provider','provider_message_id'],'message idempotency unique');
select col_is_unique('public','task_events',array['workspace_id','event_id'],'task event idempotency unique');
select col_is_unique('public','reservations',array['workspace_id','idempotency_key'],'reservation idempotency unique');
select col_is_unique('public','outbound_outbox',array['workspace_id','idempotency_key'],'outbox idempotency unique');
select col_is_unique('public','provider_events',array['workspace_id','provider','provider_event_id'],'provider event idempotency unique');
select ok((select relrowsecurity from pg_class where oid='public.conversations'::regclass),'conversations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.reservations'::regclass),'reservations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.audit_logs'::regclass),'audit logs RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.simulations'::regclass),'simulations RLS enabled');
select * from finish();
rollback;
