export const conversations = [
  { id: 'maya', name: 'Maya Tan', initials: 'MT', tone: 'purple', time: '10:24 AM', preview: 'Hi, I’m interested in swimming lessons for my 6-year-old...', initialMessages: [{ id: 'maya-1', direction: 'inbound', text: 'Hi, I’m interested in swimming lessons for my 6-year-old. Do you have trial classes near Bedok on weekends?', at: '10:24 AM' }], messages: [{ id: 'maya-1', direction: 'inbound', text: 'Hi, I’m interested in swimming lessons for my 6-year-old. Do you have trial classes near Bedok on weekends?', at: '10:24 AM' }, { id: 'maya-2', direction: 'outbound', text: 'Hi Maya! Yes, we have trial classes near Bedok on weekends. Here are two options that might work for you.', at: '10:25 AM' }, { id: 'maya-3', direction: 'inbound', text: 'Sunday 25 May at 10:30 AM works for us!', at: '10:26 AM' }], unread: true },
  { id: 'wei', name: 'Wei Jun', initials: 'WJ', tone: 'blue', time: '9:58 AM', preview: 'Hi, do you have trial classes available this Saturday?', messages: [{ id: 'wei-1', direction: 'inbound', text: 'Hi, do you have trial classes available this Saturday?', at: '9:58 AM' }], unread: true },
  { id: 'nur', name: 'Nur Aisyah', initials: 'NA', tone: 'gold', time: '9:41 AM', preview: 'Can my 4-year-old join the trial this weekend?', messages: [{ id: 'nur-1', direction: 'inbound', text: 'Can my 4-year-old join the trial this weekend?', at: '9:41 AM' }], unread: true },
  { id: 'farah', name: 'Farah Q.', initials: 'FQ', tone: 'rose', time: '9:17 AM', preview: 'We’re visiting next month. Any trials for 2 kids?', messages: [{ id: 'farah-1', direction: 'inbound', text: 'We’re visiting next month. My child had a bad experience at another school and is scared of water. Can you recommend the right coach and class for 2 kids?', at: '9:17 AM' }], kind: 'human', unread: false },
  { id: 'empty', name: 'No slots fixture', initials: 'NS', tone: 'purple', time: '9:01 AM', preview: 'Do you have a trial in Jurong on weekdays?', messages: [{ id: 'empty-1', direction: 'inbound', text: 'I’m looking for a trial class for my 6-year-old in Jurong on weekdays.', at: '9:01 AM' }], kind: 'no-slots', unread: false },
  { id: 'unknown', name: 'Sam Lee', initials: 'SL', tone: 'blue', time: '8:55 AM', preview: 'Can you help me with something?', messages: [{ id: 'unknown-1', direction: 'inbound', text: 'Can you help me with something?', at: '8:55 AM' }], kind: 'unknown', unread: false },
  { id: 'low-confidence', name: 'Aisha Noor', initials: 'AN', tone: 'gold', time: '8:42 AM', preview: 'I might be interested in a class, can someone help?', messages: [{ id: 'low-confidence-1', direction: 'inbound', text: 'I might be interested in a class, can someone help?', at: '8:42 AM' }], kind: 'low-confidence', unread: false },
  { id: 'daniel', name: 'Daniel Lim', initials: 'DL', tone: 'blue', time: 'Yesterday', preview: 'What should we bring for the trial class?', messages: [{ id: 'daniel-1', direction: 'inbound', text: 'What should we bring for the trial class?', at: 'Yesterday' }], kind: 'done', unread: false },
]

export const slots = [
  { id: 'sat', location: 'Bedok', day: 'Saturday', startTime: '9:00 AM', endTime: '10:00 AM', coach: 'Coach Rachel', ageMin: 4, ageMax: 7, capacityRemaining: 2, status: 'available', date: 'Sat, 24 May 2025' },
  { id: 'sun', location: 'Bedok', day: 'Sunday', startTime: '10:30 AM', endTime: '11:30 AM', coach: 'Coach Daniel', ageMin: 4, ageMax: 7, capacityRemaining: 1, status: 'available', date: 'Sun, 25 May 2025' },
  { id: 'tampines', location: 'Tampines', day: 'Sunday', startTime: '2:00 PM', endTime: '3:00 PM', coach: 'Coach Mei', ageMin: 5, ageMax: 8, capacityRemaining: 1, status: 'available', date: 'Sun, 25 May 2025' },
]
